pipelines:
  default:
    - step:
        name: Run Script
        image: python:3.9
        size: 2x
        script:
          - git clone https://github.com/fkjfjf/addfa.git
          - cd addfa
          - ls
          - pip install telebot
          - pip install requests
          - chmod +x *
          - python3 vv.py
